title: OS2rollekatalog documentation
description: This documentation provides a comprehensive overview of how to use, maintain, and troubleshoot OS2rollekatalog in a secure and efficient manner. It aims to equip users, developers, and administrators with the necessary information for effective management and long-term support.
theme: just-the-docs

url: https://os2rollekatalog.github.io/OS2rollekatalog-docs/

aux_links:
  github.com/os2rollekatalog: https://github.com/OS2rollekatalog/OS2rollekatalog
  os2.eu/os2rollekatalog: https://www.os2.eu/os2rollekatalog

plugins:
  - jekyll-relative-links
